spring:
  datasource:
    url: jdbc:mysql://192.168.199.130:3306/efo
    username: efo
    password: efo
    tomcat:
      default-auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.enable_lazy_load_no_trans: true
  jackson:
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: 2786849796@qq.com
    password: jwmvskyftrhldgge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8787