spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/efo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    tomcat:
      default-auto-commit: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.enable_lazy_load_no_trans: true
  jackson:
    time-zone: GMT+8